### ISSUE TITLE
Incompatibility with xaero's minimap

### ISSUE THREAD

**Issue by Gcat101** [ZZZank/ProbeJS-Legacy#2] opened 2024-03-23 18:58 UTC
When both mods are installed and `/probejs dump` is ran, a NoClassDefFoundError appears with the game not being able to find `xaero/map/region/LeveledRegion`. Tested on a bare 1.16.5 forge instance with only probe, xaeros, kubejs and its dependencies installed; also tried in a larger modpack with more mods. Log and crash report from the bare instance attempt attached.

To reproduce:
1. Start the game
2. Log into a world
3. Run `/probejs dump`
4. crash!!!!!!!11

[latest.log](https://github.com/ZZZank/ProbeJS-Forge/files/14733323/latest.log)
[crash-2024-03-23_21.52.17-server.txt](https://github.com/ZZZank/ProbeJS-Forge/files/14733330/crash-2024-03-23_21.52.17-server.txt)

**Comment by ZZZank** [comment] 2024-03-24 09:39
Confirmed to be an actual, reproducible bug, and will happen when Xareo's minimap is installed, but Xaero's worldmap not. 
And it will happen regradless of version of installed ProbeJS Legacy. 

I suspect that this is because of missing optional dependencies, because when the crash happens, ProbeJS is looking into `'xaero.common.mods.SupportXaeroWorldmap'`, apparently a class from Xaero's Worldmap. You can try to install Xaero's world map, and test if it still crashes. 

On my side, I made a rough fix to this problem, you can download it in the Actions page: https://github.com/ZZZank/ProbeJS-Forge/actions/runs/8408374466 . I will publish a new release once this fix is proven to be stable enough

**Comment by ZZZank** [comment] 2024-03-25 12:05
I've tested this fix, and it seems solid. I'm closing this issue since the new version is released now. If there're still bugs, a new issue will be nice.

**Closed as completed** 2024-03-25 12:06 UTC
Labels: bug
